config/routes.rb
TreeDeePrinter::Application.routes.draw do

  mount Resque::Server, at: '/resque'

  resources :objects do
    resources :snapshot
    get 'status'
    get 'wait'
    get 'error'
    collection do
      post 'fetch'
    end
  end

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#error"

  root :to => 'objects#index'

end

app/models/feed_item.rb
class FeedItem

  attr_accessor :title, :link, :description

  def self.popular
    feed = Feedzirra::Feed.fetch_and_parse('http://www.thingiverse.com/rss/popular')
    entries = feed.entries.select { |e| e.enclosure_url.to_s.match(/\.stl$/i) }
    entries.collect { |e| self.new( e.title, e.url, e.summary ) }
  rescue
    []
  end

  def self.recent
    feed = Feedzirra::Feed.fetch_and_parse('http://www.thingiverse.com/rss/newest')
    entries = feed.entries.select { |e| e.enclosure_url.to_s.match(/\.stl$/i) }
    entries.collect { |e| self.new( e.title, e.url, e.summary ) }
  rescue
    []
  end

  def self.featured
    feed = Feedzirra::Feed.fetch_and_parse('http://www.thingiverse.com/rss/featured')
    entries = feed.entries.select { |e| e.enclosure_url.to_s.match(/\.stl$/i) }
    entries.collect { |e| self.new( e.title, e.url, e.summary ) }
  rescue
    []
  end


  def initialize( title, link, description )
    @title = title
    @link = link
    @description = description
  end

  def image
    # Messily find the first image in the description
    @description.to_s.scan(%r{<img\s+src="([^"]+)}i).flatten.first
  end

end

app/models/object_data.rb
require 'open-uri'

class ObjectData < ActiveRecord::Base

  attr_accessible :url, :model, :uuid
  self.primary_key = 'uuid'
  before_create :generate_uuid
  has_attached_file :model, :default_url => ''
  has_many :snapshots, :foreign_key => 'object_uuid'

  def generate_uuid
    self.id = UUIDTools::UUID.random_create.to_s
  end

  def default_image
    snapshot = self.snapshots.first
    snapshot ? "http://treedee.net#{snapshot.image.url(:medium)}" : 'http://treedee.net/assets/treedeetree.png'
  end

  def fetch_model
    @uri = URI.parse( self.url )
    is_thingiverse = !!@uri.host.match(%r{thingiverse\.com$}) rescue false
    if is_thingiverse
      return handle_html if @uri.path.match %r{^/thing:}
      return handle_derivative if @uri.path.match %r{^/derivative:}
      return handle_stl  if @uri.path.match %r{^/download:}
    else
      return handle_stl if @uri.path.match %r{\.stl$}i
    end
    raise 'Bad URL. Is it at thingiverse?'
  end

  def handle_stl
    @uri.open do |f|

      mersh = Mersh.new( f )
      data = mersh.to_json('threejs')
      
      file = StringIO.new( data )
      metaclass = class << file; self; end
      filename = @uri.path.to_s[1..-1] + '.js'
      metaclass.class_eval do
        define_method(:original_filename) { filename }
        define_method(:content_type) { 'application/json' }
      end
      
      self.model = file
      self.save
    end
  end

  def handle_derivative
    # http://www.thingiverse.com/derivative:42587
    # First, check for STL links. If there are none, go to the original object:
    @uri.open do |f|
      doc = Nokogiri::HTML( f )
      
      # <div class="thing-file" id="thing-file-93009" data-adddate="2012-10-08 19:34:03" data-dlcount="6" data-filetype="stl">
      stl_files = doc.search('.thing-file[data-filetype=stl]')
      if stl_files.empty?
        href = doc.search('#instance-meta a').select { |l| l.attr('href').match(/thing:\d+$/) }.first.attr('href') rescue nil
        raise "Could not find a link to a thing" unless href
        @uri = URI.join( @uri, href )
        handle_html
      else
        href = stl_files.first.search('a').first.attr('href') rescue nil
        raise "Could not find STL download link" unless href
        @uri = URI.join( @uri, href )
        handle_stl
      end
    end    
  end

  def handle_html
    @uri.open do |f|
      doc = Nokogiri::HTML( f )
      
      # <div class="thing-file" id="thing-file-93009" data-adddate="2012-10-08 19:34:03" data-dlcount="6" data-filetype="stl">
      stl_files = doc.search('.thing-file[data-filetype=stl]') 
      if stl_files.empty?
        stl_files = doc.search('.thing-file[data-filetype=STL]')
        raise "No STL files found at #{@uri.to_s}!" if stl_files.empty?
      end

      href = stl_files.first.search('a').first.attr('href') rescue nil
      raise "Could not find STL download link" unless href

      @uri = URI.join( @uri, href )
      handle_stl
    end
  end

  def self.request!( id )
    $redis.set "#{self.class.name}:#{id}:status", 'requested'
    $redis.set "#{self.class.name}:#{id}:last_update", Time.now
  end

  def self.complete!( id )
    $redis.set "#{self.class.name}:#{id}:status", 'complete'
    $redis.set "#{self.class.name}:#{id}:last_update", Time.now
  end

  def self.error!( id, error )
    $redis.set "#{self.class.name}:#{id}:status", 'error'
    $redis.set "#{self.class.name}:#{id}:error_message", error.to_s
    $redis.set "#{self.class.name}:#{id}:last_update", Time.now
  end

  def self.status?( id )
    $redis.get "#{self.class.name}:#{id}:status"
  end

  def self.error_message( id )
    $redis.get "#{self.class.name}:#{id}:error_message"
  end

  def self.last_update?( id )
    $redis.get "#{self.class.name}:#{id}:last_update"
  end

end

app/models/snapshot.rb
require 'base64'

class Snapshot < ActiveRecord::Base

  attr_accessible :data, :object_uuid, :snap_type
  attr_accessor :data
  belongs_to :object_data, :foreign_key => 'object_uuid'
  has_attached_file :image, :styles => { :thumb => "80x80>", :medium => "200x200>" }
  validates_attachment_presence :image
  before_validation :get_image, :on => :create

  def self.recent
    self.order('created_at desc').take(6)
  end

  def object
    self.object_data
  end

  def get_image
    data = Base64.decode64( @data.gsub(%r{^data:([^;]+);base64,},'') )
    mime_type = $1 || 'image/png'
    file_ext = mime_type.split('/').last
    file = StringIO.new( data )
    metaclass = class << file; self; end
    filename = "snapshot.#{file_ext}"
    metaclass.class_eval do
      define_method(:original_filename) { filename }
      define_method(:content_type) { mime_type }
    end
    self.image = file
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
end

app/controllers/objects_controller.rb
class ObjectsController < ApplicationController

  def index
    # http://www.thingiverse.com/rss/popular
    if params[:error]
      @error_message = ObjectData.error_message( params[:error] )
    end
    render layout: 'front'
  end

  def show
    @object = ObjectData.find( params[:id] )
  end

  def wait
    @id = params[:object_id]
  end

  def status
    render :json => { status: ObjectData.status?( params[:object_id] ) }
  end

  def fetch
    raise URI::InvalidURIError if params[:url].empty?
    object = ObjectData.find_or_create_by_url( params[:url] )
    if object.model.exists?
      redirect_to object_url( object.id )
    else
      ObjectData.request!( object.id )
      Resque.enqueue( GetModelWorker, object.id )
      redirect_to object_wait_url( object.id )
    end
  rescue URI::InvalidURIError
    redirect_to root_url, alert: 'Invalid URL specified. Is it at thingiverse?'
  rescue Exception
    redirect_to root_url, alert: $!.to_s
  end

end

app/controllers/snapshot_controller.rb
class SnapshotController < ApplicationController

  def create
    @snapshot = Snapshot.create( data: params[:data], object_uuid: params[:object_id], snap_type: params[:type] )
    render :json => {
      id: @snapshot.id,
      url: object_snapshot_url( @snapshot.object_uuid, @snapshot.id, :download => 1 )
    }
  end

  def show
    if @snapshot = Snapshot.where( :object_uuid => params[:object_id], :id => params[:id] ).first
      if params[:download]
        send_file @snapshot.image.path, :filename => "snapshot-#{@snapshot.id}.png"
      else
        redirect_to @snapshot.image.url
      end
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/objects_helper.rb
module ObjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- | (• ◡•)| (❍ᴥ❍ʋ) -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TreeDee" %></title>
    <%= yield :header %>
    <meta property="fb:admins" content="662214578" />
    <meta property="fb:app_id" content="527278637301509" />
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag '/assets/icon.png', :rel => 'shortcut icon' %>
    <link href='http://fonts.googleapis.com/css?family=Marcellus' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><i></i> TreeDee</a>
          <div class="container nav-collapse">
            <ul class="nav">              
              <li><a href="#aboutModal" data-toggle="modal">About</a></li>
              <li><a href="#glassesModal" data-toggle="modal">3D Glasses?</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
        <div id="social-media">
          <%= yield :social_media %>
        </div>
      </div>
    </div>

    <div id="container" class="container-fluid">

      <div class="content">
              <%= yield %>
      </div><!--/content-->

    </div> <!-- /container -->

    <div id="aboutModal" class="modal hide fade in" style="display: none; ">  
      <div class="modal-header">  
        <a class="close" data-dismiss="modal">×</a>  
        <h3>About</h3>  
      </div>  
      <div class="modal-body">    
        <p>This site exists half way between the realm of humor and valuable learning exercises. 
          Thanks to the awesome friend who told me "do it" when I decided to share the joke one morning.</p>
        <p>Built on <a href="http://rubyonrails.org/">Rails</a>, <a href="http://threejs.org">three.js</a>, and <a href="http://rubygems.org/gems/mersh">mersh</a>.</p>
        <p>Long live <b>#VegasTech</b>!</p>
        <p style="text-align: right">-<a href="http://twitter.com/makenai">@makenai</a></p>
      </div>
    </div>  

    <div id="glassesModal" class="modal hide fade in" style="display: none; ">  
      <div class="modal-header">  
        <a class="close" data-dismiss="modal">×</a>  
        <h3>3D Glasses?</h3>  
      </div>  
      <div class="modal-body">    
        <p>To see 3D you're probably going to need a pair of red and blue 3D 
          glasses. The old kind. Like this: <img src="/assets/3d_glasses.png" alt="3D glasses" />.</p>
        <p>You can find some for free <a href="http://free-3d-glasses.com/">here</a> or.. (while 
          supplies last) you can send a self addressed stamped envelope to:</p>
        <p>Pawel Szymczykowski<br />
          2280 Corporate Circle #100<br />
          Henderson, NV 89074</p>
      </div>
    </div>  


    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36237720-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>

    <script type="text/javascript">
      var uvOptions = {};
      (function() {
        var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
        uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/LzwIH8dQou6TEkR8fDX8Q.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
      })();
    </script>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <div id="fb-root"></div>

    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=527278637301509";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

  </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<!-- | (• ◡•)| (❍ᴥ❍ʋ) -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TreeDee" %></title>
    <%= csrf_meta_tags %>
    <%= yield :header %>    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag '/assets/icon.png', :rel => 'shortcut icon' %>
    <link href='http://fonts.googleapis.com/css?family=Marcellus' rel='stylesheet' type='text/css'>
  </head>
  <body id="front">

    <div class="container">

      <div id="social-media">
        <div class="fb-like" data-href="http://treedee.net" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
        <a href="https://twitter.com/share" data-text="How can you do 3D printing without a 3D printer? Harness 1980's tech!" data-url="http://treedee.net" class="twitter-share-button" data-lang="en"></a>
      </div>

      <div class="content">
              <%= yield %>
      </div>

      <footer>
        <p>brought by <a href="http://twitter.com/makenai">@makenai</a>. (with exclamation points!)</p>
      </footer>

    </div>

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-36237720-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    <script type="text/javascript">
      var uvOptions = {};
      (function() {
        var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
        uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/LzwIH8dQou6TEkR8fDX8Q.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
      })();
    </script>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <div id="fb-root"></div>

    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=527278637301509";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>    
  </body>
</html>

app/views/objects/index.html.erb
<% content_for :header do %>
  <meta property="og:title" content="TreeDee.net"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://treedee.net"/>
  <meta property="og:image" content="http://treedee.net/assets/treedeetree.png"/>
  <meta property="og:site_name" content="TreeDee.net"/>
  <meta property="og:description" content="You can print stuff in 3D without an expensive 3D printer! How? Why with 1980's technology my friend!"/>
<% end %>

<h1 id="title">TreeDee</h1>

<div id="marketing">
  <ul class="left">
    <li>Revolutionariest 3D printing software that requires no plastic filament, resins or special hardware!</li>
    <li>All you need is a color printer, paper and visual cortex!</li>
    <li>Money back guarantee.</li>
  </ul>
  <ul class="right">
    <li>Works with standard STL files and smooth, smooth integration with <a href="http://www.thingiverse.com/">Thingiverse</a>!</li>
    <li>You'll be printing out 3D objects in seconds!</li>
    <li>Completely FREE!</li>
  </ul>
  <h3>Try it right meow!</h3>
</div>

<% if flash[:alert] || @error_message %>
<div class="alert alert-error">
  <a href="#" class="close" data-dismiss="alert">×</a>
  <%= flash[:alert] || @error_message %>
</div>
<% end %>

<form id="thingiverse-form" class="form-inline" action="<%= fetch_objects_path %>" method="post">
  <div class="input-append">
    <input class="input-xxlarge" id="thingiverse-url" name="url" type="text" placeholder="Paste a Thingiverse URL here!">
    <button class="btn btn-large btn-inverse" type="submit"><i class="icon-ok icon-white"></i></button>
  </div>
</form>

<div id="feeds">

  <div id="recent">
  <h4>Recently Printed</h4>
  <% Snapshot.recent.each do |snap| %>
    <%= link_to image_tag( snap.image.url(:thumb) ), object_path( snap.object_uuid ) %>
  <% end %>
  </div>

  <% cache( { action: 'index', action_suffix: 'popular' }, expires_in: 5.minutes ) do %>
  <div id="popular">
    <h4>Featured at Thingiverse</h4>
    <% FeedItem.featured.sample(6).each do |i| %>
      <%= link_to image_tag( i.image ), fetch_objects_url( url: i.link ), method: :post, title: i.title %>
    <% end %>
  </div>
  <% end %>

</div>

<div id="sponsors">
  <h4>Cool Sites!</h4>
  <a href="http://3dprintweekly.com/" title="3D Print Weekly"><img src="/assets/3dprintweekly.png" alt="3D Print Weekly" /></a>
  <a href="http://www.thingiverse.com" title="Thingiverse"><img src="/assets/thingiverse.png" alt="Thingiverse" /></a>
</div>

app/views/objects/show.html.erb
<% content_for :header do %>
  <meta property="og:title" content="A cool model at TreeDee.net"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://treedee.net/objects/<%= @object.id %>"/>
  <meta property="og:image" content="<%= @object.default_image %>"/>
  <meta property="og:site_name" content="TreeDee.net"/>
  <meta property="og:description" content="Oh look, a cool 3D model! Why not take a look?"/>
<% end %>
<% content_for :social_media do %>
  <div class="fb-like" data-href="http://treedee.net/objects/<%= @object.id %>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
  <a href="https://twitter.com/share" data-url="http://treedee.net/objects/<%= @object.id %>" data-text="Check out this cool 3D model!" class="twitter-share-button" data-lang="en"></a>
<% end %>

<div id="loading">
  <img src="/assets/cogs204.gif" />
  Thinking about stuffs..
</div>

<div id="treedee"></div>
<script type="text/javascript">
    var modelToLoad = '<%= raw @object.model.url %>',
      modelUUID = '<%= @object.id %>';
</script>

<div id="tools">
    <a href="#" class="button" id="print">Print</a>
    <a href="#" class="button" id="image">Image</a>
    <a href="#modelInfo" data-toggle="modal" class="button" id="info">Info</a>

    <a href="#" class="button" id="zoom-in">Zoom In</a>
    <a href="#" class="button" id="zoom-out">Zoom Out</a>    
    <a href="#" class="button" id="pan-left">Left</a>
    <a href="#" class="button" id="pan-down">Down</a>
    <a href="#" class="button" id="pan-up">Up</a>
    <a href="#" class="button" id="pan-right">Right</a>
    <a href="#" class="button" id="position">Position</a>
    <div id="position-settings">
      X rotation:<br />
      <div id="x-slider"></div><input type="text" id="x-label" class="slider-label" value="0" /><br />
      Y rotation:<br />
      <div id="y-slider"></div><input type="text" id="y-label" class="slider-label" value="0" /><br />
      Z rotation:<br />
      <div id="z-slider"></div><input type="text" id="z-label" class="slider-label" value="0" /><br />
      Focal length:<br />
      <div id="focal-length-slider"></div><input type="text" id="focal-length-label" class="slider-label" value="0" />
    </div>

    <a href="#" class="button" id="threedee">Toggle 3D</a>
    <a href="#" class="button" id="material">Material</a>
    <div id="material-selector">
      <div id="swatches">
        <% %w{ 
          000000 0000AA 00AA00 00AAAA 
          AA0000 AA00AA AA5500 AAAAAA
          555555 5555FF 55FF55 55FFFF
          FF5555 FF55FF FFFF55 FFFFFF
        }.each do |color| %>
          <a href="#" class="button" style="background-color: #<%= color %>;" data-color="<%= color %>"><%= color %></a>
        <% end %>
      </div>
    </div>

</div>

  <div id="modelInfo" class="modal hide fade in" style="display: none; ">  
    <div class="modal-header">  
      <a class="close" data-dismiss="modal">×</a>  
      <h3>Model Information</h3>  
    </div>  
    <div class="modal-body">    
      <p>This model was retrieved from <%= link_to @object.url, @object.url %> on <%= @object.created_at %></p>
      <% if @object.snapshots.length > 0 %>
      <h4>Recent Snapshots</h4>
      <p>
        <% @object.snapshots.limit(5).each do |snap| %>
          <%= link_to image_tag( snap.image.url(:thumb) ), snap.image.url %>
        <% end %>
      </p>
      <% end %>
    </div>
  </div>

app/views/objects/wait.html.erb
<div id="wait">
  
  <h1>Please wait!</h1>

  <%= image_tag 'wait.gif' %>

  <h2>Fetching and processing your model...</h2>

</div>

<script type="text/javascript">
  var checkStatus = function() {
    $.getJSON('/objects/<%= @id %>/status', function( data ) {
      if ( data.status == 'requested' ) {
        setTimeout( checkStatus, 1000 );
      } else {
        if ( data.status == 'complete' ) {
          window.location = '/objects/<%= @id %>';
        } else {
          window.location = '/?error=<%= @id %>';
        }
      }
    });
  };
  checkStatus();
</script>